// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aauuhmqqvxxqhcgobywf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhdXVobXFxdnh4cWhjZ29ieXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTY4ODAsImV4cCI6MjA2MjI3Mjg4MH0.0sJiabS1A8yDZ_zbWm-3gc6RjZ3v_hreaLr_fBVQ5FA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);